---
# Example of host reservations list
# KEA_DHCP4_HOST_RESERVATIONS:
#   - hostname: "example"
#     hw-address: "00:00:00:00:00:00"
#     ip-address: "{{ KEA_SUBNET4 | ansible.netcommon.ipmath(250) }}"
KEA_DHCP4_CONFIG:
  Dhcp4:
    interfaces-config:
      interfaces:
        - "{{ FIREWALL_LAN_INTERFACE }}"
    host-reservation-identifiers:
      - hw-address
    lease-database:
      type: memfile
      persist: true
      name: /var/lib/kea/leases/dhcp4.leases
    hooks-libraries:
      - library: "/usr/lib/x86_64-linux-gnu/kea/hooks/libdhcp_run_script.so"
        parameters:
          name: "/usr/local/bin/dhcp_run_script.sh"
          sync: false
    subnet4:
      - id: 1
        subnet: "{{ KEA_SUBNET4 }}"
        pools:
          - pool: "{{ KEA_SUBNET4_POOL }}"
        option-data:
          - name: routers
            data: "{{ KEA_SUBNET4 | ansible.netcommon.ipmath(1) }}"
          - name: domain-name-servers
            data: "{{ KEA_SUBNET4 | ansible.netcommon.ipmath(1) }}"
          - name: domain-search
            data: "{{ ACME_DOMAIN_NAME }}"
        reservations: "{{ KEA_DHCP4_HOST_RESERVATIONS }}"
