---
FIREWALL_LAN_INTERFACE: "enp3s0"
FIREWALL_WAN_INTERFACE: "enp2s0"
WAN_UPLOAD_BANDWIDTH: "50mbit"
WAN_DOWNLOAD_BANDWIDTH: "50mbit"
FIREWALL_SSH_ENABLED: true
FIREWALL_OPEN_PORTS_ENABLED: true
FIREWALL_OPEN_PORTS:
  # Allow NGINX access for local services
  - INTERFACE: "{{ FIREWALL_LAN_INTERFACE }}"
    PROTOCOL: "tcp"
    PORT: "80"
  - INTERFACE: "{{ FIREWALL_LAN_INTERFACE }}"
    PROTOCOL: "tcp"
    PORT: "443"
  - INTERFACE: "{{ FIREWALL_LAN_INTERFACE }}"
    PROTOCOL: "tcp"
    PORT: "5432"
  - INTERFACE: "{{ FIREWALL_LAN_INTERFACE }}"
    PROTOCOL: "tcp"
    PORT: "53"
  - INTERFACE: "{{ FIREWALL_LAN_INTERFACE }}"
    PROTOCOL: "udp"
    PORT: "53"
FIREWALL_ADDITIONAL_RULES:
  # Allow DNS requests made by the pi-hole and their response
  - nft add rule inet filter INPUT iif enp2s0 udp sport 53 ip saddr {8.8.8.8, 8.8.4.4} accept
  - nft add rule inet filter OUTPUT oif enp2s0 udp dport 53 ip daddr {8.8.8.8, 8.8.4.4} accept
FIREWALL_LAN_MAC_RESTRICTION_ENABLED: true
FIREWALL_LAN_MAC_WHITELIST: "{{ (KEA_DHCP4_HOST_RESERVATIONS | map(attribute='hw-address') | list) + (FIREWALL_ADDITIONAL_MAC_WHITELIST | map(attribute='hw-address') | list) }}"
FIREWALL_LAN_MAC_WHITELIST_FILE: "/etc/firewall-gw/mac_address_whitelist.json"
