---
NGINX_SERVICE_NAME: "fw-nginx"
NGINX_SERVICE_SYSTEMD_DESCRIPTION: "Firewall Web Server - NGINX"
NGINX_SERVICE_SYSTEMD_REQUIRES: "docker.service"
NGINX_SERVICE_SYSTEMD_AFTER: "docker.service"
NGINX_SERVICE_SYSTEMD_FILE: "/etc/systemd/system/{{ DOCKER_COMPOSE_SERVICE_NAME }}.service"
NGINX_SERVICE_IMAGES:
  nginx:
    name: "nginx"
    tag: "1.25.5-bookworm"
NGINX_SERVICE_COMPOSE_PATH: "/etc/firewall-gw/docker-compose/nginx"
NGINX_COMPOSE_SERVICE_CONFIG_PATH: "/etc/firewall-gw/config/nginx"
NGINX_IMAGE: "{{ NGINX_SERVICE_IMAGES.nginx.name }}:{{ NGINX_SERVICE_IMAGES.nginx.tag }}"
NGINX_COMPOSE_SERVICE_CONFIG_FILES:
  - src: "{{ playbook_dir }}/templates/nginx/nginx.conf.j2"
    dest: "{{ NGINX_COMPOSE_SERVICE_CONFIG_PATH }}/nginx_top_level.conf"
    mode: 0644
    owner: "root"
    group: "root"
NGINX_SERVICE_MANIFEST:
  dest: "{{ NGINX_SERVICE_COMPOSE_PATH }}/docker-compose.yml"
  content:
    services:
      nginx:
        image: "{{ NGINX_IMAGE }}"
        network_mode: host
        volumes:
          - "{{ ACME_CERT_DIR }}:{{ ACME_CERT_DIR }}"
          - "{{ NGINX_COMPOSE_SERVICE_CONFIG_PATH }}/nginx_top_level.conf:/etc/nginx/conf.d/01_nginx_top_level.conf"
