---
JENKINS_JCASC_CONFIG:
  jenkins:
    agentProtocols:
      - "JNLP4-connect"
      - "Ping"
    authorizationStrategy:
      globalMatrix:
        entries:
          - group:
              name: "FirewallAdmin"
              permissions:
                - "Agent/Build"
                - "Agent/Configure"
                - "Agent/Connect"
                - "Agent/Create"
                - "Agent/Delete"
                - "Agent/Disconnect"
                - "Credentials/Create"
                - "Credentials/Delete"
                - "Credentials/ManageDomains"
                - "Credentials/Update"
                - "Credentials/View"
                - "Job/Build"
                - "Job/Cancel"
                - "Job/Configure"
                - "Job/Create"
                - "Job/Delete"
                - "Job/Discover"
                - "Job/Move"
                - "Job/Read"
                - "Job/Workspace"
                - "Overall/Administer"
                - "Overall/Read"
                - "Run/Delete"
                - "Run/Replay"
                - "Run/Update"
                - "SCM/Tag"
                - "View/Configure"
                - "View/Create"
                - "View/Delete"
                - "View/Read"
    clouds:
      - docker:
          name: "Docker Host"
          dockerApi:
            readTimeout: 60
            connectTimeout: 60
            dockerHost:
              uri: "unix:///var/run/docker.sock"
    securityRealm:
      oic:
        automanualconfigure: "auto"
        wellKnownOpenIDConfigurationUrl: "https://auth.{{ ACME_DOMAIN_NAME }}/application/o/jenkins/.well-known/openid-configuration"
        clientId: "{{ JENKINS_AUTHENTIK_CLIENT_ID }}"
        clientSecret: "{{ JENKINS_AUTHENTIK_CLIENT_SECRET }}"
        disableSslVerification: true
        emailFieldName: "email"
        fullNameFieldName: "name"
        groupsFieldName: "groups"
        userNameField: "preferred_username"
        scopes: "openid profile email"
  unclassified:
    location:
      url: "https://fw-jenkins.{{ ACME_DOMAIN_NAME }}/"
  appearance:
    prism:
      theme: PRISM
    themeManager:
      disableUserThemes: false
      theme: "dark"
