---
MONITORING_PROMETHEUS_CONFIG:
  global:
    scrape_interval: 10s
  scrape_configs:
    - job_name: "node_exporter"
      scrape_interval: 1s
      static_configs:
        - targets: [ "127.0.0.1:9100" ]
    - job_name: "telegraf_exporter"
      static_configs:
        - targets: [ "127.0.0.1:9273" ]
    - job_name: "powerdns_recursor_exporter"
      static_configs:
        - targets: [ "{{ PDNS_RECURSOR_WEB_SERVER_LOCAL_ADDRESS }}:{{ PDNS_RECURSOR_WEB_SERVER_LOCAL_PORT }}" ]
