---
- name: Setup LetsEncrypt SSL Certificate
  hosts: all
  gather_facts: yes
  become: True
  vars_files:
  - "{{ playbook_dir }}/extravars/acme.yml"
  - "../../Home-Ops-Internal/ansible/Linux-Firewall-Gateway/acme.yml"
  roles:
    - acme
