---
- name: Install/Upgrade Authentik
  hosts: all
  gather_facts: yes
  become: True
  vars_files:
  - "{{ playbook_dir }}/extravars/authentik.yml"
  - "../../Ansible-Secrets/Linux-Firewall-Gateway/authentik.yml"
  roles:
    - role: docker_compose_service
      DOCKER_COMPOSE_SERVICE_NAME: "{{ AUTHENTIK_SERVICE_NAME }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_DESCRIPTION: "{{ AUTHENTIK_SERVICE_SYSTEMD_DESCRIPTION }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_REQUIRES: "{{ AUTHENTIK_SERVICE_SYSTEMD_REQUIRES }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_AFTER: "{{ AUTHENTIK_SERVICE_SYSTEMD_AFTER }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_FILE: "{{ AUTHENTIK_SERVICE_SYSTEMD_FILE }}"
      DOCKER_COMPOSE_SERVICE_IMAGES: "{{ AUTHENTIK_SERVICE_IMAGES }}"
      DOCKER_COMPOSE_SERVICE_COMPOSE_PATH: "{{ AUTHENTIK_SERVICE_COMPOSE_PATH }}"
      DOCKER_COMPOSE_SERVICE_MANIFEST: "{{ AUTHENTIK_SERVICE_MANIFEST }}"

- name: Add/Update Authentik Users/Groups and Providers/Apps via OpenTofu
  connection: local
  hosts: localhost
  gather_facts: False
  become: False
  vars_files:
  - "{{ playbook_dir }}/extravars/common.yml"
  - "{{ playbook_dir }}/extravars/authentik.yml"
  - "../../Ansible-Secrets/Linux-Firewall-Gateway/acme.yml"
  - "../../Ansible-Secrets/Linux-Firewall-Gateway/authentik.yml"
  - "../../Ansible-Secrets/Linux-Firewall-Gateway/data-services.yml"
  - "../../Ansible-Secrets/Linux-Firewall-Gateway/jenkins.yml"
  roles:
    - role: opentofu
      OPENTOFU_MODULE_CONFIG_FILE_DST: "{{ AUTHENTIK_TOFU_MODULE_CONFIG_FILE_DEST }}"
      OPENTOFU_PROJECT_PATH: "{{ AUTHENTIK_TOFU_PROJECT_PATH }}"
      OPENTOFU_STATE_DB_SCHEMA_NAME: "{{ AUTHENTIK_TOFU_STATE_DB_SCHEMA_NAME }}"
      OPENTOFU_MODULE_CONFIG: "{{ AUTHENTIK_TOFU_MODULE_CONFIG }}"
      OEPNTOFU_ENV: "{{ AUTHENTIK_TOFU_ENV }}"
