---
- name: Install/Upgrade PostgreSQL and Redis
  hosts: all
  gather_facts: yes
  become: True
  vars_files:
  - "{{ playbook_dir }}/extravars/common.yml"
  roles:
    - role: linux_common
    - role: motd
