---
- name: Create/Update PostgreSQL Databases and Users Privileges
  hosts: all
  gather_facts: yes
  become: True
  vars_files:
    - "../../Home-Ops-Internal/ansible/Linux-Firewall-Gateway/data-services.yml"
  roles:
    - pgsql_dbs_users
