---
- name: Setup/Update Jenkins
  hosts: all
  gather_facts: yes
  become: True
  vars_files:
  - "{{ playbook_dir }}/extravars/jenkins/jenkins.yml"
  - "{{ playbook_dir }}/extravars/jenkins/jcasc_config.yml"
  - "{{ playbook_dir }}/extravars/jenkins/jenkins_plugins.yml"
  - "../../Ansible-Secrets/Linux-Firewall-Gateway/acme.yml"
  - "../../Ansible-Secrets/Linux-Firewall-Gateway/jenkins.yml"
  roles:
    - role: docker_compose_service
      DOCKER_COMPOSE_SERVICE_NAME: "{{ JENKINS_SERVICE_NAME }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_DESCRIPTION: "{{ JENKINS_SERVICE_SYSTEMD_DESCRIPTION }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_REQUIRES: "{{ JENKINS_SERVICE_SYSTEMD_REQUIRES }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_AFTER: "{{ JENKINS_SERVICE_SYSTEMD_AFTER }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_FILE: "{{ JENKINS_SERVICE_SYSTEMD_FILE }}"
      DOCKER_COMPOSE_SERVICE_IMAGES: "{{ JENKINS_SERVICE_IMAGES }}"
      DOCKER_COMPOSE_SERVICE_COMPOSE_PATH: "{{ JENKINS_SERVICE_COMPOSE_PATH }}"
      DOCKER_COMPOSE_SERVICE_MANIFEST: "{{ JENKINS_SERVICE_MANIFEST }}"
      DOCKER_COMPOSE_SERVICE_CONFIG_PATH: "{{ JENKINS_COMPOSE_SERVICE_CONFIG_PATH }}"
      DOCKER_COMPOSE_SERVICE_CONFIG_FILES: "{{ JENKINS_COMPOSE_SERVICE_CONFIG_FILES }}"
      DOCKER_COMPOSE_SERVICE_SET_GROUP_ID: true
