---
- name: Setup/Update Kea DHCP
  hosts: all
  gather_facts: yes
  become: True
  vars_files:
  - "{{ playbook_dir }}/extravars/firewall.yml"
  - "{{ playbook_dir }}/extravars/kea/kea.yml"
  - "{{ playbook_dir }}/extravars/kea/kea_dhcp4_config.yml"
  - "{{ playbook_dir }}/extravars/kea/kea_dhcp6_config.yml"
  - "../../Home-Ops-Internal/ansible/Linux-Firewall-Gateway/acme.yml"
  - "../../Home-Ops-Internal/ansible/Linux-Firewall-Gateway/kea.yml"
  roles:
    - role: docker_compose_service
      DOCKER_COMPOSE_SERVICE_NAME: "{{ KEA_SERVICE_NAME }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_DESCRIPTION: "{{ KEA_SERVICE_SYSTEMD_DESCRIPTION }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_REQUIRES: "{{ KEA_SERVICE_SYSTEMD_REQUIRES }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_AFTER: "{{ KEA_SERVICE_SYSTEMD_AFTER }}"
      DOCKER_COMPOSE_SERVICE_SYSTEMD_FILE: "{{ KEA_SERVICE_SYSTEMD_FILE }}"
      DOCKER_COMPOSE_SERVICE_IMAGES: "{{ KEA_SERVICE_IMAGES }}"
      DOCKER_COMPOSE_SERVICE_COMPOSE_PATH: "{{ KEA_SERVICE_COMPOSE_PATH }}"
      DOCKER_COMPOSE_SERVICE_MANIFEST: "{{ KEA_SERVICE_MANIFEST }}"
      DOCKER_COMPOSE_SERVICE_CONFIG_PATH: "{{ KEA_COMPOSE_SERVICE_CONFIG_PATH }}"
      DOCKER_COMPOSE_SERVICE_CONFIG_FILES: "{{ KEA_COMPOSE_SERVICE_CONFIG_FILES }}"
      DOCKER_COMPOSE_SERVICE_ADDITIONAL_PATHS: "{{ KEA_COMPOSE_SERVICE_ADDITIONAL_PATHS }}"
