name: Build Kea Simple Container Image
on:
  push:
    branches:
      - main
    paths:
      - "docker/kea/simple/Dockerfile"
      - ".github/workflows/kea-simple-container-image-build.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: docker/kea/simple/
          push: true
          tags: "${{ secrets.DOCKER_HUB_USERNAME }}/kea:simple-latest,${{ secrets.DOCKER_HUB_USERNAME }}/kea:simple-2.4"
