name: Build Hashicorp Vault Container Image
on:
  push:
    branches:
      - main
    paths:
      - "docker/vault/Dockerfile"
      - ".github/workflows/vault-container-image-build.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: docker/vault/
          push: true
          tags: "${{ secrets.DOCKER_HUB_USERNAME }}/vault:1.18.3,${{ secrets.DOCKER_HUB_USERNAME }}/vault:latest"
